# Generated by Django 2.2.2 on 2021-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haven', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='pin',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
